### ISSUE TITLE
[TaskExecutor/ERROR]: Error invoking listener EventListener

### ISSUE THREAD

**Issue by LingEmberMaple** [zhongbai2333/AutoMsgTitle#4]
```
[TaskExecutor/INFO] [auto_msg_title]: 配置文件已加载
[MCDR] [TaskExecutor/ERROR]: Error invoking listener EventListener[plugin=auto_msg_title@0.1.1,priority=1000,callback=<function on_load at 0x0000019D2929D4E0>]
Traceback (most recent call last):
  File "D:\Applications\Python312\Lib\site-packages\mcdreforged\plugin\plugin_manager.py", line 600, in trigger_listener
    listener.execute(listener.plugin.server_interface, *args)
  File "D:\Applications\Python312\Lib\site-packages\mcdreforged\plugin\plugin_event.py", line 106, in execute
    return self.callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins\AutoMsgTitle-v0.1.1.mcdr\auto_msg_title\__init__.py", line 196, in on_load
    CommandActions(__mcdr_server, config.permission)
  File "plugins\AutoMsgTitle-v0.1.1.mcdr\auto_msg_title\command_actions.py", line 13, in __init__
    self.data_editor = JsonDataEditor(
                       ^^^^^^^^^^^^^^^
  File "plugins\AutoMsgTitle-v0.1.1.mcdr\auto_msg_title\storage.py", line 10, in __init__
    global_data_json = self._read_data()
                       ^^^^^^^^^^^^^^^^^
  File "plugins\AutoMsgTitle-v0.1.1.mcdr\auto_msg_title\storage.py", line 17, in _read_data
    with open(self.filepath, "r") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'config\\auto_msg_title/data.json
```

**Comment by zhongbai2333** [comment]
已修复问题，正在确认是否完成修复

**Comment by zhongbai2333** [comment]
已确认于 v0.1.2 修复，请从 Releases 中获取并确认是否解决

**Comment by LingEmberMaple** [comment]
> 已确认于 v0.1.2 修复，请从 Releases 中获取并确认是否解决

**Comment by LingEmberMaple** [comment]
已解决

> 已确认于 v0.1.2 修复，请从 Releases 中获取并确认是否解决
